language: java

jdk: oraclejdk8

install: ./gradlew assemble --stacktrace

services:
  - postgresql

before_script:
  - psql -c 'create database test_idc_database;' -U postgres

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432